<?php

/**
 * @file
 * Hook implementations for bookish_toolbar.
 */

/**
 * Implements hook_page_top().
 */
function bookish_toolbar_page_top(array &$page_top) {
  $page_top['bookish_toolbar'] = [
    '#type' => 'sfc',
    '#component_id' => 'bookish_toolbar',
    '#access' => \Drupal::currentUser()->hasPermission('administer site configuration'),
    '#cache' => [
      'contexts' => ['user'],
    ],
  ];
}
